services:
  app:
    build: .
    container_name: clothing-brand-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clothing-brand-db
      SPRING_DATASOURCE_USERNAME: postgres-Clothing-Brand
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - clothing-brand-network
    restart: unless-stopped

  postgres:
    container_name: postgres_container
    image: postgres:14
    environment:
      POSTGRES_USER: postgres-Clothing-Brand
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clothing-brand-db   # ✅ auto-create DB
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - clothing-brand-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - clothing-brand-network
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.4
    container_name: "easyshop-loki"
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    networks:
      - clothing-brand-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: "easyshop-prometheus"
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9095:9090"

networks:
  clothing-brand-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
